/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlybanhang;

import backend.HangHoa;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.BufferedWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

    /**
     *
     * @author ADMIN
     */
    
public class ThemSanPham extends javax.swing.JPanel{

    /**
     * Creates new form ThemSanPham
     */
    private ArrayList<HangHoa> ListHH = new ArrayList<>();
    public ThemSanPham() {
        initComponents();
        ListHH = QLHH.postDL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        txtMVT = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        txtTenSP = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        txtNoiSX = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        txtGiaThanh = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        txtSoLuong = new javax.swing.JTextField();
        label6 = new java.awt.Label();
        txtNgayNK = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label1.setMaximumSize(new java.awt.Dimension(112, 25));
        label1.setMinimumSize(new java.awt.Dimension(112, 25));
        label1.setName(""); // NOI18N
        label1.setText("Mã Vật Tư");

        txtMVT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtMVT.setMaximumSize(new java.awt.Dimension(180, 30));
        txtMVT.setMinimumSize(new java.awt.Dimension(180, 30));
        txtMVT.setPreferredSize(new java.awt.Dimension(180, 30));
        txtMVT.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtMVTInputMethodTextChanged(evt);
            }
        });

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label2.setMaximumSize(new java.awt.Dimension(112, 25));
        label2.setMinimumSize(new java.awt.Dimension(112, 25));
        label2.setName(""); // NOI18N
        label2.setText("Tên Sản Phẩm");

        txtTenSP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTenSP.setMaximumSize(new java.awt.Dimension(180, 30));
        txtTenSP.setMinimumSize(new java.awt.Dimension(180, 30));
        txtTenSP.setPreferredSize(new java.awt.Dimension(180, 30));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label3.setMaximumSize(new java.awt.Dimension(112, 25));
        label3.setMinimumSize(new java.awt.Dimension(112, 25));
        label3.setText("Nơi Sản Xuất");

        txtNoiSX.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNoiSX.setMaximumSize(new java.awt.Dimension(180, 30));
        txtNoiSX.setMinimumSize(new java.awt.Dimension(180, 30));
        txtNoiSX.setPreferredSize(new java.awt.Dimension(180, 30));

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label4.setMaximumSize(new java.awt.Dimension(112, 25));
        label4.setMinimumSize(new java.awt.Dimension(112, 25));
        label4.setText("Giá Thành");

        txtGiaThanh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtGiaThanh.setMaximumSize(new java.awt.Dimension(180, 30));
        txtGiaThanh.setMinimumSize(new java.awt.Dimension(180, 30));
        txtGiaThanh.setPreferredSize(new java.awt.Dimension(180, 30));

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label5.setMaximumSize(new java.awt.Dimension(112, 25));
        label5.setMinimumSize(new java.awt.Dimension(112, 25));
        label5.setText("Ngày Nhập Kho");

        txtSoLuong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtSoLuong.setMaximumSize(new java.awt.Dimension(180, 30));
        txtSoLuong.setMinimumSize(new java.awt.Dimension(180, 30));
        txtSoLuong.setPreferredSize(new java.awt.Dimension(180, 30));

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label6.setMaximumSize(new java.awt.Dimension(112, 25));
        label6.setMinimumSize(new java.awt.Dimension(112, 25));
        label6.setText("Số Lượng");

        txtNgayNK.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNgayNK.setMaximumSize(new java.awt.Dimension(180, 30));
        txtNgayNK.setMinimumSize(new java.awt.Dimension(180, 30));
        txtNgayNK.setPreferredSize(new java.awt.Dimension(180, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Thêm Sản Phẩm");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoiSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayNK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaThanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(194, 194, 194))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoiSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaThanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayNK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(311, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(txtMVT.getText().equals("")||txtTenSP.getText().equals("")||txtNoiSX.getText().equals("")||txtGiaThanh.getText().equals("")||txtSoLuong.getText().equals("")||txtNgayNK.getText().equals("")){
          JFrame f = new JFrame();  
          JOptionPane.showMessageDialog(f,"Bạn Chưa nhập đủ Thông Tin.","Alert",JOptionPane.WARNING_MESSAGE);
          return;
        }
        for(HangHoa i : ListHH){
            if(i.getMVT().equals(txtMVT.getText())){
            JFrame f = new JFrame();  
            JOptionPane.showMessageDialog(f,"Mã Vật Tư Đã Tồn Tại.","Alert",JOptionPane.WARNING_MESSAGE);
            return;
            }
        }
        try{
            File file =new File("src\\datatxt\\HangHoa.txt");
          if(!file.exists()){
            file.createNewFile();
          }
          FileWriter fw = new FileWriter(file,true);
          BufferedWriter bw = new BufferedWriter(fw);
          PrintWriter pw = new PrintWriter(bw);
          pw.println();
          String add = txtMVT.getText()+"-"+txtTenSP.getText()+"-"+txtNoiSX.getText()+"-"+txtGiaThanh.getText()+"-"+txtSoLuong.getText()+"-"+txtNgayNK.getText();
          HangHoa a = new HangHoa(txtMVT.getText(),txtTenSP.getText(),txtNoiSX.getText(),txtGiaThanh.getText(),txtNgayNK.getText(),txtSoLuong.getText());
          QLHH.addSanPham(a);
          pw.print(add);
          pw.close();
          JFrame f = new JFrame();  
          JOptionPane.showMessageDialog(f,"Thêm Thành Công.","Alert",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception ex){
            
        }
        txtMVT.setText("");txtTenSP.setText("");txtNoiSX.setText("");txtGiaThanh.setText("");txtSoLuong.setText("");txtNgayNK.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void txtMVTInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtMVTInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtMVTInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JTextField txtGiaThanh;
    private javax.swing.JTextField txtMVT;
    private javax.swing.JTextField txtNgayNK;
    private javax.swing.JTextField txtNoiSX;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
