/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlybanhang;

import backend.HangHoa;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class TimKiemHangHoa extends javax.swing.JPanel {

    /**
     * Creates new form TimKiemHangHoa
     */
    private ArrayList<HangHoa> ListHH = new ArrayList<>();
    DefaultTableModel dtm = new DefaultTableModel();
    private Boolean check = true;
    public TimKiemHangHoa() {
        initComponents();
        ListHH = QLHH.postDL();
        dtm.setColumnIdentifiers(new Object[]{"Mã Vật Tư", "Tên Hàng Hóa", "Nơi Sản Xuất", "Giá Thành", "Ngày Nhập Kho", "Số Lượng"});
        tblHienThi.setModel(dtm);
    }
    public void napdulieu(){
        dtm.setRowCount(0);;
        if(cbxDulieu.getSelectedItem().equals("Mã Vật Tư")){
            for (int i=0;i<ListHH.size();i++)
                if(ListHH.get(i).getMVT().contains(txtDulieu.getText())){
                    dtm.addRow(new Object[]{ListHH.get(i).getMVT(), ListHH.get(i).getTenHang(), ListHH.get(i).getNoiSanXuat(), ListHH.get(i).getGiaThanh(), ListHH.get(i).getNgayNhapKho(), ListHH.get(i).getSoLuong()});
                    check = false;
                }
        }else{
            for (int i=0;i<ListHH.size();i++)
                if(ListHH.get(i).getTenHang().contains(txtDulieu.getText())){
                    dtm.addRow(new Object[]{ListHH.get(i).getMVT(), ListHH.get(i).getTenHang(), ListHH.get(i).getNoiSanXuat(), ListHH.get(i).getGiaThanh(), ListHH.get(i).getNgayNhapKho(), ListHH.get(i).getSoLuong()});
                    check = false;
                }
        }
        if(check){
            dtm.addRow(new Object[]{"null","null","null","null","null"});
        }
                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDulieu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHienThi = new javax.swing.JTable();
        cbxDulieu = new javax.swing.JComboBox<>();

        txtDulieu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDulieu.setMaximumSize(new java.awt.Dimension(70, 30));
        txtDulieu.setMinimumSize(new java.awt.Dimension(70, 30));
        txtDulieu.setPreferredSize(new java.awt.Dimension(70, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Tìm Kiếm");
        jButton1.setMaximumSize(new java.awt.Dimension(77, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(77, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(77, 30));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        tblHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblHienThi.setRowHeight(25);
        jScrollPane1.setViewportView(tblHienThi);

        cbxDulieu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbxDulieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Vật Tư", "Tên Sản Phẩm" }));
        cbxDulieu.setMaximumSize(new java.awt.Dimension(100, 30));
        cbxDulieu.setMinimumSize(new java.awt.Dimension(100, 30));
        cbxDulieu.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxDulieu, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDulieu, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDulieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDulieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        napdulieu();
        
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxDulieu;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHienThi;
    private javax.swing.JTextField txtDulieu;
    // End of variables declaration//GEN-END:variables
}
