/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlybanhang;

import backend.HangHoa;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class XoaSanPham extends javax.swing.JPanel {

    /**
     * Creates new form XoaSanPham
     */
    private ArrayList<HangHoa> ListHH = new ArrayList<>();
    DefaultTableModel dtm = new DefaultTableModel();
    private Boolean check = false;
    public XoaSanPham() {
        initComponents();
        ListHH = QLHH.postDL();
        dtm.setColumnIdentifiers(new Object[]{"Mã Vật Tư", "Tên Hàng Hóa", "Nơi Sản Xuất", "Giá Thành", "Ngày Nhập Kho", "Số Lượng"});
        tabHienThi.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMVT = new javax.swing.JTextField();
        btnKtra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabHienThi = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Mã Vật Tư");
        jLabel1.setMaximumSize(new java.awt.Dimension(65, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(65, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(65, 25));

        txtMVT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtMVT.setMaximumSize(new java.awt.Dimension(180, 30));
        txtMVT.setMinimumSize(new java.awt.Dimension(180, 30));
        txtMVT.setPreferredSize(new java.awt.Dimension(180, 30));

        btnKtra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKtra.setText("Kiểm Tra");
        btnKtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKtraMouseClicked(evt);
            }
        });

        tabHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabHienThi);

        btnRemove.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRemove.setText("Xóa Sản Phẩm");
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMVT, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(btnKtra, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKtra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKtraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKtraMouseClicked
        // TODO add your handling code here:
         for (int i=0;i<ListHH.size();i++)
                if(ListHH.get(i).getMVT().contains(txtMVT.getText())){
                    dtm.addRow(new Object[]{ListHH.get(i).getMVT(), ListHH.get(i).getTenHang(), ListHH.get(i).getNoiSanXuat(), ListHH.get(i).getGiaThanh(), ListHH.get(i).getNgayNhapKho(), ListHH.get(i).getSoLuong()});
                    check = true;
                }
        if(!check){
            dtm.addRow(new Object[]{"null","null","null","null","null"});
        }
    }//GEN-LAST:event_btnKtraMouseClicked

    private void btnRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseClicked
        // TODO add your handling code here:
        if(check){
           QLHH.RemoveSanPham(txtMVT.getText());
           txtMVT.setText("");
           dtm.removeRow(0);
        }
    }//GEN-LAST:event_btnRemoveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKtra;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabHienThi;
    private javax.swing.JTextField txtMVT;
    // End of variables declaration//GEN-END:variables
}
