/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlybanhang;

import backend.DonHang;
import backend.HangHoa;
import java.io.File;
import java.io.FileWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class XuLyDonHang extends javax.swing.JPanel {

    /**
     * Creates new form XuLyDonHang
     */
    private ArrayList<DonHang> ListDH = new ArrayList<>();
    DefaultTableModel dtm = new DefaultTableModel();
    public XuLyDonHang() {
        initComponents();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now =LocalDateTime.now();
        datetime.setText(dtf.format(now));
        getDate();
        dtm.setColumnIdentifiers(new Object[]{"Mã Vật Tư", "Tên Khách Hàng ", "Địa Chỉ", "Số Điện Thoại", "Ngày Đặt Hàng", "Số Lượng","Tổng Tiền","Trạng Thái"});
        tblHienThi.setModel(dtm);
        napdulieu();
    }
    public void napdulieu(){
        dtm.setRowCount(0);
        for (int i=0;i<ListDH.size();i++)
            dtm.addRow(new Object[]{ListDH.get(i).getMVT(), ListDH.get(i).getTen(), ListDH.get(i).getDiaChi(), ListDH.get(i).getSDT(), ListDH.get(i).getNgayDH(), ListDH.get(i).getSL(),ListDH.get(i).getTT(),(i==0?"Đang Chờ Xử LÝ":"Đang Trong Hàng Chờ")});
    }
    public void getDate(){
        try{
            File dataHH  = new File("src\\datatxt\\DonHang.txt");        
            if(dataHH.exists()){
                Scanner read = new Scanner(dataHH);
                while(read.hasNext()){
                    Scanner line = new Scanner(read.nextLine());
                    String data = new String();
                    data = line.nextLine();
                    String[] mydata = data.split("-");
                    DonHang tmpDonHang = new DonHang(mydata[0],mydata[1],mydata[2],mydata[3],mydata[4],mydata[5],mydata[6]);
                    ListDH.add(tmpDonHang);
                }
            }else System.out.println("ERROR!!");
            
        }catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblHienThi = new javax.swing.JTable();
        label1 = new java.awt.Label();
        cbxVanchuyen = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        labGVC = new javax.swing.JLabel();
        datetime = new java.awt.Label();
        label3 = new java.awt.Label();
        button1 = new java.awt.Button();

        tblHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblHienThi);

        label1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label1.setMaximumSize(new java.awt.Dimension(120, 25));
        label1.setMinimumSize(new java.awt.Dimension(120, 25));
        label1.setText("Đơn vị vận chuyển");

        cbxVanchuyen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbxVanchuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Viettel Post", "Giao Hàng Nhanh", "Giao Hàng Tiết Kiệm" }));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Giá Vận Chuyển");
        jLabel1.setMaximumSize(new java.awt.Dimension(120, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(120, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 25));

        labGVC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labGVC.setText("20.000 VNĐ");
        labGVC.setMaximumSize(new java.awt.Dimension(120, 25));
        labGVC.setMinimumSize(new java.awt.Dimension(120, 25));
        labGVC.setPreferredSize(new java.awt.Dimension(120, 25));

        datetime.setAlignment(java.awt.Label.CENTER);
        datetime.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        datetime.setMaximumSize(new java.awt.Dimension(120, 25));
        datetime.setMinimumSize(new java.awt.Dimension(120, 25));
        datetime.setText("yyyy/mm/dd hh-mm-ss");

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label3.setMaximumSize(new java.awt.Dimension(120, 25));
        label3.setMinimumSize(new java.awt.Dimension(120, 25));
        label3.setText("Ngày Xuất Kho: ");

        button1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button1.setLabel("Xuất Đơn Hàng");
        button1.setName(""); // NOI18N
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labGVC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxVanchuyen, 0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(datetime, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxVanchuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datetime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labGVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        datetime.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
        String name = ListDH.get(0).getTen().replace(" ", "");
        String url = "src\\datatxt\\"+ListDH.get(0).getMVT()+ListDH.get(0).getTen()+".txt";
        try {
            FileWriter fw = new FileWriter(url);
            String sbill = ListDH.get(0).getMVT()+"-"+ListDH.get(0).getTen()+"-"+ListDH.get(0).getDiaChi()+"-"+ListDH.get(0).getSDT()+"-"+ListDH.get(0).getNgayDH()+"-"+ListDH.get(0).getSL()+"-"+ListDH.get(0).getTT()+"\n"+"Đơn Vị Vận Chuyển: "+cbxVanchuyen.getSelectedItem()+" "+"Giá Vận Chuyển: "+labGVC.getText()+"Ngày Xuất Kho: "+datetime.getText()+"\n"+"Người Xử Lý"+QLHH.UserLogin;
                fw.write(sbill);
            fw.close();
        } catch (Exception e) {
        }
        ListDH.remove(0);
        napdulieu();
        try {
            FileWriter fw = new FileWriter("src\\datatxt\\DonHang.txt");
            for(DonHang i : ListDH){
                String s = i.getMVT()+"-"+i.getTen()+"-"+i.getDiaChi()+"-"+i.getSDT()+"-"+i.getNgayDH()+"-"+i.getSL()+"-"+i.getTT()+"\n";
                fw.write(s);
            }
            fw.close();
        } catch (Exception e) {
        }
        JFrame f = new JFrame();  
        JOptionPane.showMessageDialog(f,"Xử Lý Đơn Hàng Thành Công.","Alert",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_button1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JComboBox<String> cbxVanchuyen;
    private java.awt.Label datetime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labGVC;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private javax.swing.JTable tblHienThi;
    // End of variables declaration//GEN-END:variables
}
